version: '3.8'

services:
  ai-engine:
    build: ./ai_engine
    command: python main.py
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./data:/app/data

  api-service:
    build: ./api_service
    ports:
      - "8000:8000"
      
  telegram-bot:
    build: ./telegram_bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}

  web-ui:
    build: ./web_ui
    ports:
      - "3000:3000"
      
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: soccerai
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
