name: iOS Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install --project-directory=ios
    - name: Build IPA
      uses: yukiarrr/ios-build-action@v1.5.0
      with:
        project-path: ios/SoccerAI.xcodeproj
        p12-base64: ${{ secrets.IOS_P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.IOS_PROVISION_BASE64 }}
        code-signing-identity: 'iPhone Distribution'
        team-id: ${{ secrets.APPLE_TEAM_ID }}
        certificate-password: ${{ secrets.IOS_CERT_PASSWORD }}
        workspace-path: ios/SoccerAI.xcworkspace
        scheme: SoccerAI
        export-method: app-store

    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ios/build/SoccerAI.ipa
        apple-id: ${{ secrets.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
